### ISSUE TITLE
Linux to Windows not working - Clipboard change not recognized

### ISSUE THREAD

**Issue by fentas** [songokas/clipboard-sync#3]
I added `config.yml` to both systems.
Started `clipboard-sync` with `-v debug`
If I copy text from windows it will send and sync to Linux.
If I copy text on Linux nothing happens. Seems that it does not recognize the clipboard change.

Using manjaro (plasma - wayland).

Not sure, guess something to do with `klipper`

**Comment by fentas** [comment]
If I do
```sh
echo test | xclip -selection clipboard
```

It works, and it is recognized.

**Comment by songokas** [comment]
I am not familiar with wayland and its protocols for clipboard communication, but reading a bit, wayland clipboard is not supported  and unless you use some software to synchronize x11 and wayland clipboard automatically,
you would have to do something like:

```
wl-paste | xclip -selection clipboard
```

https://github.com/bugaevc/wl-clipboard

I see there is a pull request to add support for it, so it could potentially be done, but this would require some time

https://github.com/aweinstock314/rust-clipboard/pull/65
